2016-08-29 18:48:30,594 [Thread-188:8256] [django.request:98] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /reg
2016-08-30 10:02:43,296 [Thread-9:2996] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-08-30 10:48:05,762 [Thread-3:5652] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-08-30 10:53:09,594 [Thread-5:11692] [django.request:170] [base:get_response] [WARNING]- Not Found: /ad/2016/08/01.jpg
2016-08-30 10:53:53,161 [Thread-25:4116] [django.request:170] [base:get_response] [WARNING]- Not Found: /ad/2016/08/01.jpg
2016-08-30 10:54:00,757 [Thread-27:6840] [django.request:170] [base:get_response] [WARNING]- Not Found: /ad/2016/08/01.jpg
2016-08-30 10:54:05,880 [Thread-28:3532] [django.request:170] [base:get_response] [WARNING]- Not Found: /ad/2016/08/01.jpg
2016-08-30 10:55:35,628 [Thread-43:5848] [django.request:170] [base:get_response] [WARNING]- Not Found: /upload/ad/2016/08/timg.jpg
2016-08-30 10:55:47,559 [Thread-44:11544] [django.request:170] [base:get_response] [WARNING]- Not Found: /upload/ad/2016/08/timg.jpg
2016-08-30 10:56:15,967 [Thread-52:12760] [django.request:170] [base:get_response] [WARNING]- Not Found: /upload/ad/2016/08/timg.jpg
2016-08-30 11:03:38,262 [Thread-148:1556] [django.request:170] [base:get_response] [WARNING]- Not Found: /archive/uploads/ad/2016/08/03.jpg
2016-08-30 11:03:38,374 [Thread-149:6596] [django.request:170] [base:get_response] [WARNING]- Not Found: /archive/uploads/ad/2016/08/4e4a20a4462309f730a702bc700e0cf3d6cad650.jpg
2016-08-30 11:03:42,404 [Thread-151:3532] [django.request:170] [base:get_response] [WARNING]- Not Found: /archive/uploads/ad/2016/08/03.jpg
2016-08-30 11:03:42,407 [Thread-152:6840] [django.request:170] [base:get_response] [WARNING]- Not Found: /archive/uploads/ad/2016/08/4e4a20a4462309f730a702bc700e0cf3d6cad650.jpg
2016-08-30 11:03:48,411 [Thread-159:3388] [django.request:170] [base:get_response] [WARNING]- Not Found: /archive/uploads/ad/2016/08/03.jpg
2016-08-30 11:03:48,423 [Thread-160:1604] [django.request:170] [base:get_response] [WARNING]- Not Found: /archive/uploads/ad/2016/08/4e4a20a4462309f730a702bc700e0cf3d6cad650.jpg
2016-08-30 11:04:07,976 [Thread-166:1040] [django.request:170] [base:get_response] [WARNING]- Not Found: /category/uploads/ad/2016/08/03.jpg
2016-08-30 11:04:08,112 [Thread-167:5328] [django.request:170] [base:get_response] [WARNING]- Not Found: /category/uploads/ad/2016/08/4e4a20a4462309f730a702bc700e0cf3d6cad650.jpg
2016-08-30 11:04:16,266 [Thread-168:4016] [django.request:170] [base:get_response] [WARNING]- Not Found: /category/uploads/ad/2016/08/4e4a20a4462309f730a702bc700e0cf3d6cad650.jpg
2016-08-30 11:04:24,171 [Thread-169:13872] [django.request:170] [base:get_response] [WARNING]- Not Found: /category/uploads/ad/2016/08/03.jpg
2016-08-30 11:04:31,608 [Thread-174:11176] [django.request:170] [base:get_response] [WARNING]- Not Found: /category/uploads/ad/2016/08/4e4a20a4462309f730a702bc700e0cf3d6cad650.jpg
2016-08-30 11:08:09,864 [Thread-3:5240] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\workspaceofpython\blog_project\blog\views.py", line 46, in index
    return render(request,'index.html',locals())
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\defaulttags.py", line 1014, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\workspaceofpython\venv\program\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'url('index')', expected 'empty' or 'endfor'
2016-10-08 10:14:09,595 [Thread-25:9716] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-10-08 10:14:39,926 [Thread-65:12800] [django.request:170] [base:get_response] [WARNING]- Not Found: /uploads/avatar/default.png
2016-10-24 15:03:17,519 [MainThread:12760] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Nicky1Wu\Desktop\blog_project\blog\views.py", line 49, in index
    return render(request,'index.html',locals())
  File "D:\python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python27\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python27\lib\site-packages\django\template\loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: index.html
2016-10-24 15:04:09,382 [MainThread:12760] [django.request:170] [base:get_response] [WARNING]- Not Found: /static/css/base.css
2016-10-24 15:04:09,394 [MainThread:12760] [django.request:170] [base:get_response] [WARNING]- Not Found: /static/js/jquery.min.js
2016-10-24 15:04:09,403 [MainThread:12760] [django.request:170] [base:get_response] [WARNING]- Not Found: /static/css/index.css
2016-10-24 15:04:09,411 [MainThread:12760] [django.request:170] [base:get_response] [WARNING]- Not Found: /static/js/sliders.js
2016-10-24 15:04:09,427 [MainThread:12760] [django.request:170] [base:get_response] [WARNING]- Not Found: /static/js/nav.js
2016-10-24 15:07:07,696 [Thread-48:8108] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-10-24 15:09:30,509 [Thread-43:12568] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-10-24 15:10:26,121 [Thread-50:5692] [django.request:170] [base:get_response] [WARNING]- Not Found: /collected/css/index.css
2016-10-24 17:14:57,589 [Thread-2:1868] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Nicky1Wu\Desktop\blog_project\blog\views.py", line 49, in index
    return render(request,'index.html',locals())
  File "D:\python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\python27\lib\site-packages\django\template\base.py", line 209, in render
    with context.bind_template(self):
  File "D:\python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "D:\python27\lib\site-packages\django\template\context.py", line 237, in bind_template
    processors = (template.engine.template_context_processors +
  File "D:\python27\lib\site-packages\django\utils\functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\python27\lib\site-packages\django\template\engine.py", line 90, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
  File "D:\python27\lib\site-packages\django\template\engine.py", line 90, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
  File "D:\python27\lib\site-packages\django\utils\module_loading.py", line 33, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "D:\python27\lib\site-packages\django\utils\module_loading.py", line 29, in import_string
    return getattr(module, class_name)
ImportError: Module "blog.views" does not define a "global_setting" attribute/class
2016-10-24 17:16:43,164 [Thread-2:5144] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Nicky1Wu\Desktop\blog_project\blog\views.py", line 49, in index
    return render(request,'index.html',locals())
  File "D:\python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\python27\lib\site-packages\django\template\base.py", line 209, in render
    with context.bind_template(self):
  File "D:\python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "D:\python27\lib\site-packages\django\template\context.py", line 237, in bind_template
    processors = (template.engine.template_context_processors +
  File "D:\python27\lib\site-packages\django\utils\functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\python27\lib\site-packages\django\template\engine.py", line 90, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
  File "D:\python27\lib\site-packages\django\template\engine.py", line 90, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
  File "D:\python27\lib\site-packages\django\utils\module_loading.py", line 33, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "D:\python27\lib\site-packages\django\utils\module_loading.py", line 29, in import_string
    return getattr(module, class_name)
ImportError: Module "blog.views" does not define a "global_setting" attribute/class
2016-10-24 17:18:33,900 [Thread-25:580] [django.request:170] [base:get_response] [WARNING]- Not Found: /123
2016-10-24 17:21:38,096 [Thread-2:6300] [django.request:170] [base:get_response] [WARNING]- Not Found: /123
2016-10-24 17:21:41,305 [Thread-3:12520] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Nicky1Wu\Desktop\blog_project\blog\views.py", line 49, in index
    return render(request,'index.html',locals())
  File "D:\python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\python27\lib\site-packages\django\template\base.py", line 209, in render
    with context.bind_template(self):
  File "D:\python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "D:\python27\lib\site-packages\django\template\context.py", line 237, in bind_template
    processors = (template.engine.template_context_processors +
  File "D:\python27\lib\site-packages\django\utils\functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\python27\lib\site-packages\django\template\engine.py", line 90, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
  File "D:\python27\lib\site-packages\django\template\engine.py", line 90, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
  File "D:\python27\lib\site-packages\django\utils\module_loading.py", line 33, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "D:\python27\lib\site-packages\django\utils\module_loading.py", line 29, in import_string
    return getattr(module, class_name)
ImportError: Module "blog.views" does not define a "global_setting" attribute/class
2016-10-30 22:48:09,466 [Thread-26:14852] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
